### ISSUE TITLE
Bikeshed: Module names

### ISSUE THREAD

**Issue by jimmycuadra** [ruma/ruma-client-api#10]
Before publishing this crate, I'd like to settle on good names for the modules for each API endpoint. As always, it's tough to pick good names. Although the naming doesn't affect the functionality of the library, it does affect user experience. We want to strike the right balance between semantics and intuition.

Here are the guidelines I've been using for naming API endpoints' modules:

* The name should be a verb describing the client is taking, e.g. `get_some_resource`.
* Endpoints which are basic CRUD operations should use the prefixes `create`, `get`, `update`, and `delete`.
* The prefix `set` is preferred to `create` if the resource is a singleton. In other words, when there's no distinction between `create` and `update`.

Here are the modules whose names I'm not entirely happy with right now:

* `r0::sync`: This contains all endpoints for "getting" events, yet it's named after the one endpoint in that group that doesn't start with `get`. A contributor previously added a separate `events` module for the ones prefixed with `get`, but that left the actual `/sync` endpoint as the lone endpoint within the top-level `sync` module. There isn't really a big semantic distinction between "getting" and "syncing" events, so I combined them. `events` doesn't seem like the right name, cause the idea is that they're endpoints for _getting_ events. After all, _everything_ in Matrix is an event.
* `r0::presence::{get_subscribed_presences, update_presence_subscriptions}`: The spec refers to the user's presence subscriptions as a "presence list," but this doesn't seem intuitive to me. However, the current names aren't super obvious either. Maybe we can do better.
* `r0::typing::start_or_stop_typing`: The current name feels a bit awkward. Initially it was called `set_typing`. That name didn't seem quite right, because the user is not _setting typing_, they're _typing_. Also, as mentioned above, the `set` prefix should be used for singleton resources, and while typing is a singleton in concept, using this API creates _new_ `m.typing` events each time, so it's really more like a "create" operation.

If anyone has thoughts on naming for the above modules, or has concerns or ideas about other modules in the crate, let's use this issue to discuss them.

**Comment by vberger** [comment]
Regarding the grouping in modules: a possibility could be to more or less mimic the structure of [the spec](http://matrix.org/docs/spec/client_server/r0.2.0.html), so for example end up with a structure like `events::sync`, `events::get::state_for_key`, `events::send::state_for_key`, etc...

This is just a thought, I have no strong conviction about that to be honest.

**Comment by jimmycuadra** [comment]
Confusingly, the [Swagger docs](https://matrix.org/docs/api/client-server/) use yet another categorization of endpoints. I started this crate by going over both the Swagger docs and the spec side by side to come up with categories that I thought were the best combination of "correct" and intuitive.

**Comment by vberger** [comment]
Regarding specifically `sync::get_state_event_by_event_type` and `sync::get_state_event_by_state_key` (as they are named currently). I find these names misleading.

the associated endpoints are:

- `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}`
- `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}`

According to the spec, the first one differs with the second in that *it forces the state key to be the empty string*, but both will return the state for a given event type and a given state key.

OTOH, the current module names imply in my opinion that one only filters by state key while the other only filters by event type.

**Comment by jplatte** [comment]
Re `r0::typing::start_or_stop_typing`: Does `create_typing_event` sound good?

**Comment by iinuwa** [comment]
Re `r0::presence::{get_subscribed_presences, update_presence_subscriptions}`: This has been removed from the spec, so we don't have to worry about naming it anymore. :)

**Comment by iinuwa** [comment]
If you guys want a newbie perspective: for the `sync` endpoint, what do we think about breaking up the events in `sync` and `send` by type, removing `send` altogether, and just leaving `sync_events in `sync`? For example,

```
r0::membership::{get_member_events, ... <all the other endpoints currently in membership>}
r0::message::{get_message_event, send_message_event}
r0::state::{get_state_events, get_state_events_for_empty_key, get_state_events_for_key,  send_state_event_for_empty_key, send_state_event_for_key}
r0::sync::sync_events
```
I think this helps show that to send or receive events of a specific type, you use the specific module, and the `sync` module is for receiving all types of events in order to catch up.

This would also remove the need for the `send` module. I don't know about whether it feels ergonomic or not to use `message::send_message_event` vs `send::send_message_event`, but it seems to be consistent with how we handle all other events (e.g. creating typing events uses the `typing` module, creating receipt events uses `receipt` module, etc.). Perhaps those endpoints could even use the same CRUD verbiage as well (`message::create_message_event` as opposed to `message::send_message_event`).

Sorry if this is off base or if this was already discussed somewhere else that I missed.

**Comment by jimmycuadra** [comment]
Good suggestions, @iinuwa! Go ahead and make those changes if you like.

**Comment by iinuwa** [comment]
With that, I think that the three questions in this issue have been addressed. Should we close it?

**Comment by jplatte** [comment]
Yeah, if new naming issues come up we can open a new issue.
