### ISSUE TITLE
Use duration and datetime types for applicable fields

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#116]
@valkum pointed out on [#ruma:matrix.org](https://matrix.to/#/#ruma:matrix.org) that it would make sense to use `std::time::Duration` for the `timeout` parameter in `sync_events::Request`.

We should look into creating custom (de)serialization functions for `Duration` ~~(or maybe import `chrono` because it provides a better 'datetime' type and also use its `Duration` type then)~~ and updating all applicable fields.

Edit: I've had a closer look at the time crate's, the chrono crate's and std's API. I'm pretty sure std::time will be sufficient for our needs.

**Comment by iinuwa** [comment]
Endpoints with duration parameters:
- [ ] [sync](https://github.com/ruma/ruma-client-api/blob/26d7e2f04d66ff8eff8c7555e68982c4db437940/src/r0/sync/sync_events.rs#L51)
- [ ] [request openid token](https://github.com/ruma/ruma-client-api/blob/master/src/r0/account/request_openid_token.rs#L32)
- [ ] [claim keys](https://github.com/ruma/ruma-client-api/blob/master/src/r0/keys/claim_keys.rs#L26)
- [ ] [get keys](https://github.com/ruma/ruma-client-api/blob/master/src/r0/keys/get_keys.rs#L26)
- [ ] [create typing events](https://github.com/ruma/ruma-client-api/blob/master/src/r0/typing/create_typing_event.rs#L23)
- [ ] [VOIP TURN server](https://github.com/ruma/ruma-client-api/blob/master/src/r0/voip/get_turn_server_info.rs#L22)

**Comment by jplatte** [comment]
Since timestamps in the spec like `origin_server_ts` don't carry any timezone information, it would equally make sense to use `std::time::SystemTime` for these.

**Comment by iinuwa** [comment]
endpoints with timestamps:

- [ ] server/get_user_info.rs
- [ ] media/get_media_preview.rs
- [ ] push/get_notifications.rs
- [ ] device.rs

**Comment by jplatte** [comment]
Remaining parts done in befc55e, 207b77b and 6ddb9ec.
