### ISSUE TITLE
Update member list endpoint

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#120]
The member list endpoint is missing request parameters: [GET /_matrix/client/r0/rooms/{roomId}/members](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-members)

See the Matrix spec for more information.

**Comment by iinuwa** [comment]
@jplatte , this should be good to close, right?

**Comment by jplatte** [comment]
@iinuwa Yeah, thanks for noticing!
