### ISSUE TITLE
Add serde default attribute to non-required, non-Option fields

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#130]
Using `#serde[*with]` seems to cause problems with deserialization if the `default` tag is not also specified. Places where this is used should updated to add the default tag.

**Comment by jplatte** [comment]
Actually when fixing this problem for `/sync` I looked for and didn't find any other occurrences. But it won't hurt to double-check that.

**Comment by iinuwa** [comment]
I also checked, and it looks good. I'll close this.
