### ISSUE TITLE
Use BTreeMap for all map types.

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#134]
- [x] Replace all uses of `serde_json::Map` and `std::collections::HashMap` with `BTreeMap`.
- [ ] Make a note in [CONTRIBUTORS.md](/ruma/ruma-client-api/blob/master/CONTRIBUTORS.md) to use that type for all map types.
- [ ] Mark this as a breaking change in [CHANGELOG.md](/ruma/ruma-client-api/blob/master/CHANGELOG.md).

Cf. https://github.com/ruma/ruma-client-api/issues/132#issuecomment-610014354

**Comment by jplatte** [comment]
I'm still not 100% certain which should be our future standard map type – `BTreeMap` would mean all keys are sorted lexically; does that buy us anything? The other option would be `HashMap`.

**Comment by jplatte** [comment]
I've read about the differences again and think `BTreeMap` does make more sense for us. `HashMap`s are faster when there is a large amount of entries, but that is very unlikely to ever be the case for our use cases. Trying to DOS something based on our map uses seems like it would be prevented by JSON size limitations.

**Comment by iinuwa** [comment]
This was done in c5689f3, but the CHANGELOG.md and CONTRIBUTING.md files should be updated to mention this convention now.

**Comment by jplatte** [comment]
Change log updated in fc976a5.

**Comment by jplatte** [comment]
`CONTRIBUTING.md` updated in 8443213.
