### ISSUE TITLE
Normalize serde_json imports

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#138]

**Comment by jplatte** [comment]
In particular:

* `serde_json::Value` should be imported as `JsonValue`
* `serde_json::{from_to}_{string,value}` should be imported as `{from,to}_json_{string,value}`
* all `serde_json::Map` imports should be removed as part of #134

**Comment by iinuwa** [comment]
Do we want to add serde_json::{from_slice, to_vec} to this list?

And do you intend `serde_json::from_str as from_json_string` or `from_json_str`?

**Comment by iinuwa** [comment]
Oh, and do you want all json comparisons to use the `json!` macro instead of raw strings (`r#" { ... } "#)?

**Comment by jplatte** [comment]
> Do we want to add serde_json::{from_slice, to_vec} to this list?

Yes.

> And do you intend `serde_json::from_str as from_json_string` or `from_json_str`?

Yeah, that sounds good.

> Oh, and do you want all json comparisons to use the `json!` macro instead of raw strings (`r#" { ... } "#)?

That would be good too, yeah.
