### ISSUE TITLE
Rename client_exchange module

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#160]
There was discussion on #ruma: matrix.org that the fact that the client_exchange module didn't follow the specification terminology, it made it harder to find. Renaming it to something like to_device may be better.

**Comment by jplatte** [comment]
Yeah, I agree. Will change it soon.

**Comment by jplatte** [comment]
Done in e5adfe1181d0fa8f32955b396d859407b4e43b82.
