### ISSUE TITLE
create_message_event has wrong type for data field

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#161]
This should be `serde_json::value::RawValue`, with the docs noting to use `serde_json::value::to_raw_value`. `create_state_event_for_*` should be updated from `serde_json::Value` to the same.

**Comment by jplatte** [comment]
@poljar Do you think this is a good interim solution until https://github.com/ruma/ruma-events/issues/47 (event content collections) is solved? Alternatively, we could implement event content collections without macros first and use them here earlier, I guess that mostly depends on whether somebody puts in the necessary work.

**Comment by poljar** [comment]
I think it's fine for now.

**Comment by jplatte** [comment]
Fixed in b809db81f46c180449273b67604b304efb672bb8.
