### ISSUE TITLE
ruma_client_api::r0::push::get_pushrules_all::Response should contain ruma_events::push_rules::PushRulesEventContent or ruma_events::push_rules::Ruleset

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-client-api#175]
Endpoint: https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushrules
Event: https://matrix.org/docs/spec/client_server/r0.6.0#m-push-rules

**Comment by jplatte** [comment]
Done in da4abacf69142bf6aa5986ebf185a136a55888c7.
