### ISSUE TITLE
CreationContent needs predecessor field

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-client-api#176]
https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-createroom
https://matrix.org/docs/spec/client_server/r0.6.0#m-room-create
ruma_client_api::r0::room::create_room::CreationContent

https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$3sPYFfDw98hrTtms3KRe86Ia426gJYK-e9LvGXsuoCo?via=t2l.io&via=matrix.org&via=koesters.xyz

Timo:
> Can clients put a predecessor into the CreationContent of /createRoom

TravisR:
> if they want to, yes. 

Note: We don't need creator or room_version because the server will override them

**Comment by jplatte** [comment]
Done in 429e5a5.
