### ISSUE TITLE
avatar_url in set_avatar_url should be optional

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-client-api#178]
This is so that you can remove your avatar_url again

ruma_client_api::r0::profile::set_avatar_url::Request

https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-profile-userid-displayname

**Comment by jplatte** [comment]
Fixed in 9e198132d0f60bf0850a2c745e04118a5347c3c1.
