### ISSUE TITLE
/sync response can be optimized

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-client-api#192]
Currently, if a room has no updates, ruma outputs `{"summary":{},"unread_notifications":{},"timeline":{"events":[]},"state":{"events":[]},"account_data":{"events":[]},"ephemeral":{"events":[]}}`
which could just be left out from the `join` field entirely

ruma_client_api::r0::sync::sync_events::Response
more specifically: ruma_client_api::r0::sync::sync_events::JoinedRoom
but it's probably the case for more structs as well.

https://matrix.org/docs/spec/client_server/unstable#get-matrix-client-r0-sync

**Comment by jplatte** [comment]
We can easily skip fields with serde, but we can't really filter out object or array entries. You'll have to make sure not to add empty entries yourself.
