### ISSUE TITLE
New endpoint from r0.3.0: /media/r0/preview_url

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-client-api#39]
Docs can be found [here](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-media-r0-preview-url).

This is somewhat of a tricky endpoint in that it seems to return arbitrary (or at least rather complex) JSON. I'm not sure if we want to declare the response to optionally contain every single available OpenGraph property or if we want to declare the response to be `serde_json::Value` (or some wrapper around it) and in the latter case, how that would be implemented (might need changes to ruma-api-macros).

**Comment by jimmycuadra** [comment]
Ideally we'd use an existing OpenGraph crate, but from a search on crates.io I'm not setting anything that does quite what we'd want. Using `serde_json::Value` is probably fine.
