### ISSUE TITLE
Add or update endpoints for requesting account management tokens.

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#60]
3 endpoints for requesting tokens to manage various aspects of accounts were added in r0.4.0:
- `POST /account/3pid/msisdn/requestToken`
- `POST /register/msisdn/requestToken`
- `POST /account/password/msisdn/requestToken`

It seems that the corresponding endpoints for emails are incomplete and should be updated as well.

**Comment by iinuwa** [comment]
@jplatte, I'm working on this now, so you can assign it to me.

**Comment by iinuwa** [comment]
Do we need to add identifiers for `SessionId` and/or `ClientSecret`, or should we just leave it as a `String`?

**Comment by jplatte** [comment]
I thought about the many string types in the spec too yesterday. For now, let's keep using `String` for things that don't have a more concrete type yet. We can always refine the types later.
