### ISSUE TITLE
Add key management endpoints

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#64]
The following endpoints for key management are missing:
- [GET /_matrix/client/r0/keys/changes](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-keys-changes)
- [POST /_matrix/client/r0/keys/claim](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-keys-claim)
- [POST /_matrix/client/r0/keys/query](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-keys-query)
- [POST /_matrix/client/r0/keys/upload](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-keys-upload)

See the links to the Matrix spec for more details.

**Comment by Karlinde** [comment]
I've begun working on this
