### ISSUE TITLE
Add push notifications endpoints.

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#66]
The endpoints for push notifications are missing:

### Pusher Management 
- [GET /_matrix/client/r0/pushers](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushers)
- [POST /_matrix/client/r0/pushers/set](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-pushers-set)

### Notifications
- [GET /_matrix/client/r0/notifications](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-notifications)

### Push Rule Management
- [GET /_matrix/client/r0/pushrules/](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushrules)
- [DELETE /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}](https://matrix.org/docs/spec/client_server/r0.6.0#delete-matrix-client-r0-pushrules-scope-kind-ruleid)
- [GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushrules-scope-kind-ruleid)
- [PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}](https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-pushrules-scope-kind-ruleid)
- [GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushrules-scope-kind-ruleid-actions)
- [PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions](https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-pushrules-scope-kind-ruleid-actions)
- [GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-pushrules-scope-kind-ruleid-enabled)
- [PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled](https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-pushrules-scope-kind-ruleid-enabled)

**Comment by jplatte** [comment]
This seems like it might be tricky (in addition to it just being a bunch of work because of the many endpoints). There's wording like this (GET `/_matrix/client/r0/pushrules`):

> Clients can "drill-down" on the rulesets by suffixing a scope to this path e.g. /pushrules/global/. This will return a subset of this data under the specified key e.g. the global key.

which sounds to me like we can't map those endpoints from the spec one-to-one to endpoints in ruma-client-api.

**Comment by iinuwa** [comment]
Should I split this into multiple issues then?

**Comment by iinuwa** [comment]
RE: scoped push rules
Can we either:
- specify the scope as an optional path parameter,
- or create a separate endpoint that takes a (kind of how we're handling the `get_state_events_for_key` and `get_state_events_for_empty_key`)?

**Comment by jplatte** [comment]
I think it's fine to have one issue for all these endpoints. One can still create a PR for an individual endpoint.

Re. scoped push rules: optional path parameters would probably need special treatment in ruma-api-macros. Creating multiple ruma_api! endpoints for the one spec endpoint is what I meant.

**Comment by Karlinde** [comment]
I couldn't keep myself from starting on this so you can assign it to me if no one else badly wants to do it.

**Comment by iinuwa** [comment]
Go for it!
