### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by jimmycuadra** [ruma/ruma-client-api#8]
I mistakenly left out the `#![deny(missing_docs)]` attribute when first starting this crate, and as a result we've ended up with a lot of missing documentation. We'll now be warned for missing docs, but if we can fill in the ones that are missing, then we can deny missing docs to ensure new code is documented as we go.

**Comment by Nauxuron** [comment]
Shouldn't this issue be closed, seeing that `#![deny(missing_docs)]` has been in `lib.rs` for quite some time now?

**Comment by jplatte** [comment]
Yes, you're right.
