### ISSUE TITLE
Add optional `unstable_features` endpoint to `/versions` response

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#83]
Added in r0.5.0

**Comment by jplatte** [comment]
Note for anyone wanting to work on this: It probably makes sense here (and for other endpoint updates) to have a look at the current (r0.6.0) spec for the endpoint and cross-check it with ruma-client-api to make sure the changelog didn't forget anything. The doc comment should be updated with the endpoint declaration (to `r0.6.0`, not `r0.6.0.html`, as the former seems to be the canonical URL).
