### ISSUE TITLE
Add SSO Login endpoint

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#87]
[GET /login/sso/redirect](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-login-sso-redirect) is missing.

See the link to the Matrix spec for more information.

**Comment by jplatte** [comment]
Labeling as hard because this will need investigation / discussion on how to integrate the http redirect with ruma-client (and might required changes to ruma-api).
