### ISSUE TITLE
Update sync endpoint

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#91]
The following modifications to the `GET /sync` endpoint  need to be made:
  - Add `online` and `unavailable` variants to `SetPresence` (0.4.0/matrix-org/matrix-doc#1141)
  - Add `device_one_time_keys_count` to response (0.4.0/matrix-org/matrix-doc#1284)
  - Add `to_device` parameter

There may be other changes necessary, so so the [spec documentation](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-sync) for more information.

**Comment by iinuwa** [comment]
I'm starting on this one. I'll wait till #123 is merged though.

**Comment by iinuwa** [comment]
@jplatte, it looks like you added [this TODO comment](https://github.com/ruma/ruma-client-api/blob/master/src/r0/sync/sync_events.rs#L210). Were you thinking to add a collection of AccountData events to ruma-events?

**Comment by jplatte** [comment]
I'm not sure, that comment is clearly incomplete :man_facepalming: 

It seems likely that's what that comment should have been about. But I'm not sure whether there even is a distinction to be made between AccountData events and the current `collections::only::Event`s / `NonRoomEvent`s.

**Comment by iinuwa** [comment]
It doesn't seem like the [spec on Client Config/Account Data](https://matrix.org/docs/spec/client_server/r0.6.0#module-account-data) has anything to say about what types of events can go in Account Data. It can probably just stay as a collection of `NonRoomEvent`s.
