### ISSUE TITLE
Clarify whether joined members endpoint response properties are optional

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#97]
Cf [joined_members.rs](https://github.com/ruma/ruma-client-api/blob/master/src/r0/membership/joined_members.rs#L32).

**Comment by iinuwa** [comment]
@jplatte, it looks like you added this comment a year ago. Do you know why you suspected these shouldn't be optional? I'd probably just say let's follow the spec as is by making both fields optional and be done with it.

**Comment by jplatte** [comment]
@iinuwa I'm guessing that was just me knowing next to nothing to Matrix' internals and assuming users would always have a display name, even if it's just their user id / user id localpart or sth. like that.

Just making the display name optional and adding `#[serde(skip_serializing_if)]` to both should be good.
